# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller build specification for Arduino Studio.

    python -m PyInstaller --noconfirm arduino_studio.spec

Produces a single folder build at ``dist/Arduino Studio/`` containing
``Arduino Studio.exe`` - that is the recommended layout for this app because the
executable has to shell out to ``arduino-cli`` and keep its log folder next to
a writable directory (see README.md, "Building a standalone .exe").

The spec is deliberately defensive: the icon is generated by
``tools/make_icon.py`` and is optional, so a fresh clone builds fine without
ever running that script.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files, collect_dynamic_libs, collect_submodules

ROOT = Path(SPECPATH).resolve()  # noqa: F821  (injected by PyInstaller)

# collect_submodules()/collect_data_files() below import the package, which only
# works when the project root is on sys.path (PyInstaller does not guarantee that).
import sys  # noqa: E402

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
RESOURCES = ROOT / "arduino_studio" / "resources"
ICON = RESOURCES / "arduino.ico"


def _app_version() -> tuple[int, int, int, int]:
    """Read ``__version__`` from the package - the single source of truth."""
    text = (ROOT / "arduino_studio" / "__init__.py").read_text(encoding="utf-8")
    match = re.search(r"^__version__\s*=\s*[\"']([^\"']+)[\"']", text, re.M)
    numbers = [int(part) for part in re.findall(r"\d+", match.group(1) if match else "0.0.0")]
    numbers = (numbers + [0, 0, 0, 0])[:4]
    return tuple(numbers)  # type: ignore[return-value]


def _ensure_version_file() -> str | None:
    """Write (or reuse) ``arduino_studio/resources/version_info.txt``.

    The file is a PyInstaller version resource, so the built exe shows a real
    file description and version in its Properties box.  Everything is
    best-effort: if anything goes wrong the build simply gets no version info.
    """
    target = RESOURCES / "version_info.txt"
    try:
        number = _app_version()
    except Exception:  # pragma: no cover - unreadable package metadata
        return None
    if target.is_file():
        cached = target.read_text(encoding="utf-8", errors="replace")
        if ".".join(str(part) for part in number) in cached:
            return str(target)  # up to date
        # a stale file would stamp the new exe with the previous version number
        try:
            target.unlink()
        except OSError:  # pragma: no cover - locked by an editor
            return str(target)
    try:
        text = ".".join(str(part) for part in number)
        RESOURCES.mkdir(parents=True, exist_ok=True)
        body = "\n".join([
            "# UTF-8",
            "VSVersionInfo(",
            "  ffi=FixedFileInfo(",
            f"    filevers={number},",
            f"    prodvers={number},",
            "    mask=0x3F,",
            "    flags=0x0,",
            "    OS=0x40004,",
            "    fileType=0x1,",
            "    subtype=0x0,",
            "    date=(0, 0),",
            "  ),",
            "  kids=[",
            "    StringFileInfo([",
            "      StringTable(",
            "        '040904B0',",
            "        [",
            "          StringStruct('CompanyName', 'Arduino Studio'),",
            "          StringStruct('FileDescription', 'Arduino Studio - standalone Arduino IDE'),",
            f"          StringStruct('FileVersion', '{text}'),",
            "          StringStruct('InternalName', 'ArduinoStudio'),",
            "          StringStruct('OriginalFilename', 'Arduino Studio.exe'),",
            "          StringStruct('ProductName', 'Arduino Studio'),",
            f"          StringStruct('ProductVersion', '{text}'),",
            "        ],",
            "      )",
            "    ]),",
            "    VarFileInfo([VarStruct('Translation', [1033, 1200])]),",
            "  ],",
            ")",
            "",
        ])
        target.write_text(body, encoding="utf-8")
    except Exception:  # pragma: no cover - cosmetic only
        return None
    return str(target)


# ------------------------------------------------------------------ data files
datas: list[tuple[str, str]] = []

# CustomTkinter ships its themes (JSON) and fonts as package data; without them
# the frozen app raises on ``set_default_color_theme``.
datas += collect_data_files("customtkinter")

# Arduino Studio's own package data (the window icon, the generated version
# resource) has to travel with it, because the running app looks for those files
# relative to ``arduino_studio/__init__.py`` - which inside a bundle is
# ``sys._MEIPASS/arduino_studio``.
datas += collect_data_files("arduino_studio")

if ICON.is_file():
    datas.append((str(ICON), "arduino_studio/resources"))
    datas.append((str(ICON), "."))  # the one-file lookup path (sys._MEIPASS)

binaries: list[tuple[str, str]] = []
# pyserial loads the platform backend lazily; win32 needs the C extension.
binaries += collect_dynamic_libs("serial")

hiddenimports: list[str] = []

# CRITICAL: ``arduino_studio.ui`` resolves its public names lazily through a PEP 562
# module-level ``__getattr__`` (so that ``--help``/``--check`` never import Tk), which
# means PyInstaller's static import graph only sees the empty ``ui/__init__.py`` and
# would ship an exe that dies with "No module named 'arduino_studio.ui.app'".
# Collecting the package's submodules puts every UI module in the bundle.
try:
    hiddenimports += collect_submodules("arduino_studio")
except Exception as exc:  # pragma: no cover - only if the package is not importable
    print(f"[spec] collect_submodules('arduino_studio') failed: {exc}")
    hiddenimports += [
        "arduino_studio.main",
        "arduino_studio.ui",
        "arduino_studio.ui.app",
        "arduino_studio.ui.theme",
        "arduino_studio.ui.icons",
        "arduino_studio.ui.syntax",
        "arduino_studio.ui.code_editor",
        "arduino_studio.ui.editor_tabs",
        "arduino_studio.ui.findbar",
        "arduino_studio.ui.serial_monitor",
        "arduino_studio.ui.terminal_panel",
        "arduino_studio.ui.libraries_panel",
        "arduino_studio.ui.bootloader_panel",
        "arduino_studio.ui.settings_view",
        "arduino_studio.ui.setup_wizard",
        "arduino_studio.ui.widgets.dialogs",
        "arduino_studio.ui.widgets.toolbar",
        "arduino_studio.ui.widgets.explorer",
        "arduino_studio.ui.widgets.console",
        "arduino_studio.ui.widgets.text_view",
        "arduino_studio.ui.widgets.data_table",
        "arduino_studio.ui.widgets.status_bar",
        "arduino_studio.ui.widgets.project_dialog",
    ]
hiddenimports = list(dict.fromkeys(hiddenimports + [
    "arduino_studio.core.examples",       # bundled example sketches (data-ish module)
    "serial",
    "serial.serialutil",
    "serial.tools.list_ports",
    "serial.tools.list_ports_common",
    "serial.tools.list_ports_windows",
    "serial.win32",
    "tkinter",
    "tkinter.filedialog",
    "tkinter.messagebox",
    "tkinter.font",
    "tkinter.ttk",
    "customtkinter",
    "json",
    "logging.handlers",
    "typing_extensions",
]))

for optional in ("send2trash",):  # installed only if you asked for it
    try:
        __import__(optional)
    except Exception:
        continue
    hiddenimports.append(optional)

a = Analysis(
    [str(ROOT / "run.py")],
    pathex=[str(ROOT)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "pytest",
        "doctest",
        "numpy",
        "pandas",
        "scipy",
        "matplotlib",
        "IPython",
        "PIL",
        "setuptools",
        "pip",
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)  # noqa: F821

exe = EXE(  # noqa: F821
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Arduino Studio",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=os.environ.get("UPX", "").lower() in ("1", "true", "yes"),
    console=False,  # no black console window behind the GUI
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(ICON) if ICON.is_file() else None,
    version=_ensure_version_file(),
)

coll = COLLECT(  # noqa: F821
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=os.environ.get("UPX", "").lower() in ("1", "true", "yes"),
    upx_exclude=[],
    name="Arduino Studio",
)
